/*
 * KEYPAD_PRIVATE.h
 *
 * Created: 10/22/2023 10:59:44 PM
 *  Author: Mahmoud Tariq
 */ 


#ifndef KEYPAD_PRIVATE_H_
#define KEYPAD_PRIVATE_H_


void KeyPad_vidWriteRows(u8 pattern);
void KeyPad_vidReadcols(pu8 add);
u8 SYMBOLS[16] = {
	KEYPAD_KEY_1_SYMBOL,KEYPAD_KEY_2_SYMBOL,KEYPAD_KEY_3_SYMBOL,KEYPAD_KEY_4_SYMBOL,
	KEYPAD_KEY_5_SYMBOL,KEYPAD_KEY_6_SYMBOL,KEYPAD_KEY_7_SYMBOL,KEYPAD_KEY_8_SYMBOL,
	KEYPAD_KEY_9_SYMBOL,KEYPAD_KEY_10_SYMBOL,KEYPAD_KEY_11_SYMBOL,KEYPAD_KEY_12_SYMBOL,
	KEYPAD_KEY_13_SYMBOL,KEYPAD_KEY_14_SYMBOL,KEYPAD_KEY_15_SYMBOL,KEYPAD_KEY_16_SYMBOL
};

#endif /* KEYPAD_PRIVATE_H_ */